#pragma config(Sensor, in1,    gyro,           sensorNone)
#pragma config(Sensor, in2,    manipulator,    sensorPotentiometer)
#pragma config(Sensor, in3,    mogo,           sensorPotentiometer)
#pragma config(Sensor, in4,    lift,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  L,              sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, R,              sensorQuadEncoder)
#pragma config(Motor,  port1,           rollers,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           manipulatorL,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           baseLfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           baseLback,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           baseRfront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           baseRback,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           manipulatorR,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mogo,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const unsigned short trueSpeed[128] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 21 , 21, 21, 22, 22, 22, 23, 24, 24,
	25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
	28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
	37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
	41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
	46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
	52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
	71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
	80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
	88, 89, 89, 90, 90,127,127,127
};

//LINEAR DRIVE VARIABLES
int threshold = 10;
int speedLeft;
int speedRight;
string rightDrive= "rightDrive";
string leftDrive = "leftDrive";

void driveL(int speed){
	motor[baseLfront] = speed;
  motor[baseLback] = speed;
}

void driveR(int speed){
	motor[baseRfront] = speed;
  motor[baseRback] = speed;
}

void dr4b(int speed){
	motor[liftL] = 127;
	motor[liftR] = 127;
}
void translational(int speed){
	motor[manipulatorL] = speed;
	motor[manipulatorR] = speed;
}

void drive(int speed){
	motor[baseRfront] = speed;
  motor[baseRback] = speed;
  motor[baseLfront] = speed;
  motor[baseLback] = speed;
}

void pDrive(int target){
  SensorValue[L] = 0;
  SensorValue[R] = 0;

  double kp = 0;
  int kc = 60;
  int brake = -60;
  int dir = 1; //forward
  if(target < 0){ //backward
    dir = 0;
    brake = -brake;
  }
	int left, right, errorL, errorR, speedL, speedR;
  while(1){
    left = SensorValue(L);
    right = SensorValue(R);
    errorL = target-left;
    errorR = target - right;
    speedL = errorL * kp;
    speedR = errorR *kp;

    //speed normalization
    if(dir == 1 && speedL < kc) speedL = kc;
    if(dir == 0 && speedL > -kc) speedL = -kc;
    if(dir == 1 && speedR < kc) speedR = kc;
    if(dir == 0 && speedR > -kc) speedR = -kc;

    driveL(speedL);
    driveR(speedR)

    if(dir == 0 && errorL > 0) break;
    if(dir == 1 && errorL < 0) break;
  }
  drive(-brake);
  delay(200);
  drive(0); // stop drive
}

//SETSPEED FUNCTION
void setSpeed(){
    if(speedLeft > 127) speedLeft = 127;
    if(speedLeft < -127) speedLeft = -127;
		if(speedRight > 127) speedRight = 127;
    if(speedRight < -127) speedRight = -127;
    int absSpeedL = trueSpeed[abs(speedLeft)]*(speedLeft/abs(speedLeft+0.0001));
		int absSpeedR = trueSpeed[abs(speedRight)]*(speedRight/abs(speedRight+0.0001));
    	driveL(absSpeedL);
    	driveR(absSpeedR);
}

task partner(){
	while(true){
		speedLeft = vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2];
		speedRight = vexRT[Ch3Xmtr2] -  vexRT[Ch4Xmtr2];
		setSpeed();
	}
}
task solo(){
	while(true){
		speedLeft = vexRT[Ch3] + vexRT[Ch4];
		speedRight = vexRT[Ch3] -  vexRT[Ch4];
		setSpeed();
	}
}
void autostack(){
	int pot;
	while(SensorValue[sonar] < 11 && SensorValue[sonar] != 1){
		dr4b(127);
	}
	pot = SensorValue[lift];
	while(SensorValue[manipulator] > 200){
		dr4b(75);
		translational(-127);
	}
	translational(-10);
	while(SensorValue[lift] < pot){
		dr4b(-127);
	}
	motor[rollers] = 127;
	dr4b(0);
	wait1Msec(100);
	dr4b(127);
	wait1Msec(500);
}
task main()
{
	startTask(partner);
	while(true)
	{
		motor[rollers] = (vexRT[Btn5U]*127) - (vexRT[Btn5D]*127) - 30;
		if(vexRT[Btn7L]){
			autostack();
		}
		if(vexRT[Btn8R]){
				if(SensorValue(manipulator) > 100){
					translational(-127);
				}
				else{
					translational(-10);
				}
		}
		else if(abs(vexRT(Ch2)) > 10){
			translational(vexRT[Ch2]);
		}

		else if(vexRT[Btn8D]){
			if(SensorValue(manipulator) < 2100){
				translational(127);
			}
			else{
				translational(10);
			}
		}
		else{
			translational(0);
		}

		motor[mogo] = (vexRT(Btn7U)*127) - (vexRT[Btn7D]*127);

		motor[liftL] = (vexRT(Btn6U)*127) - (vexRT[Btn6D]*127);
		motor[liftR] = (vexRT(Btn6U)*127) - (vexRT[Btn6D]*127);;
	}
}
