#pragma config(Sensor, in1,    liftL,          sensorPotentiometer)
#pragma config(Sensor, in2,    liftR,          sensorPotentiometer)
#pragma config(Sensor, in3,    manipulator,    sensorNone)
#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  ultrasonic,     sensorSONAR_inch)
#pragma config(Motor,  port1,           rollers,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           liftL1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftL2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveR,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           manipulator,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           manipulator,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftR1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           driveL,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          mogo,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const unsigned short trueSpeed[128] =
{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 21 , 21, 21, 22, 22, 22, 23, 24, 24,
	25, 25, 25, 25, 26, 27, 27, 28, 28, 28,
	28, 29, 30, 30, 30, 31, 31, 32, 32, 32,
	33, 33, 34, 34, 35, 35, 35, 36, 36, 37,
	37, 37, 37, 38, 38, 39, 39, 39, 40, 40,
	41, 41, 42, 42, 43, 44, 44, 45, 45, 46,
	46, 47, 47, 48, 48, 49, 50, 50, 51, 52,
	52, 53, 54, 55, 56, 57, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 67, 68, 70,
	71, 72, 72, 73, 74, 76, 77, 78, 79, 79,
	80, 81, 83, 84, 84, 86, 86, 87, 87, 88,
	88, 89, 89, 90, 90,127,127,127
};

//LINEAR DRIVE VARIABLES
int threshold = 10;
int speedLeft;
int speedRight;
string rightDrive= "rightDrive";
string leftDrive = "leftDrive";

//SETSPEED FUNCTION
void setSpeed(){
    if(speedLeft > 127) speedLeft = 127;
    if(speedLeft < -127) speedLeft = -127;
		if(speedRight > 127) speedRight = 127;
    if(speedRight < -127) speedRight = -127;
    int absSpeedL = trueSpeed[abs(speedLeft)]*(speedLeft/abs(speedLeft+0.0001));
		int absSpeedR = trueSpeed[abs(speedRight)]*(speedRight/abs(speedRight+0.0001));
    	motor[driveL] = absSpeedL;
    	motor[driveR] = absSpeedR;
}


task main()
{

while(true){

	motor[liftL1] = (vexRT[Btn6U] * 127) + (vexRT[Btn6D] * -127);
	motor[liftL2] = (vexRT[Btn6U] * 127) + (vexRT[Btn6D] * -127);
	motor[liftR1] = (vexRT[Btn6U] * 127) + (vexRT[Btn6D] * -127);
	motor[liftR2] = (vexRT[Btn6U] * 127) + (vexRT[Btn6D] * -127);
	motor[mogo] = (vexRT[Btn5U] * 127) + (vexRT[Btn5D] * -127);
	speedLeft = vexRT[Ch3] + vexRT[Ch4];
	speedRight = vexRT[Ch3] -  vexRT[Ch4];
	motor[rollers] = (vexRT[Btn7U] * 127) + (vexRT[Btn7D] * -157) + 30;
	setSpeed();
}
}
